# Generated by Django 2.2 on 2022-11-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=10000)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
